databases:
  - name: icici-transaction-db
    plan: free
    databaseName: icici_transactions
    user: icici_admin

services:
  - type: web
    name: icici-transaction-analyser
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: DATABASE_URL
        fromDatabase:
          name: icici-transaction-db
          property: connectionString
